### ISSUE TITLE
Problem with task

### ISSUE THREAD

**Issue by Hydro8** [logic-dev/VieraControl#1]
Hi

Thank for your work, i just buy a new panasonic TV and i try to use your library with my home automation system (write in c#).

I add VieraControl.dll on my references and try this code :

```
using Constellation;
using Constellation.Host;
using System;
using System.Net;
using System.Collections.Specialized;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Panasonic
{
    public class Program : PackageBase
    {

        private VieraControl.Client client;
        private bool connected = false;

        static void Main(string[] args)
        {
            PackageHost.Start<Program>(args);
        }

        public override void OnStart()
        {
            
VieraControl.Client client = new VieraControl.Client();
            Task<bool> finder = client.FindTV();
            finder.ContinueWith(_ =>
            {
                if (finder.Result)
                {
                    Console.WriteLine("Found TV");
                }
                else
                {
                    Console.WriteLine("No TV found");
                }
            }, TaskScheduler.FromCurrentSynchronizationContext());

        }
    }
}
```

But i've got this error :

> [ALPHA_UI/Panasonic] 16:53:11 : Critical Error : System.InvalidOperationException: The current SynchronizationContext may not be used as a TaskScheduler.
   at System.Threading.Tasks.SynchronizationContextTaskScheduler..ctor()
   at System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext()
   at Panasonic.Program.OnStart() in c:\Users\e.laville\Documents\Visual Studio 2013\Projects\Panasonic\Panasonic\Program.cs:line 40

Any idea ?

Thank

**Comment by logic-dev** [comment]
Try this

```csharp
        private VieraControl.Client client;
        private bool connected = false;
        private TaskScheduler tsContext;
        

        static void Main(string[] args)
        {
            tsContext = TaskScheduler.FromCurrentSynchronizationContext();
            PackageHost.Start<Program>(args);
        }

        public override void OnStart()
        {

VieraControl.Client client = new VieraControl.Client();
            Task<bool> finder = client.FindTV();
            finder.ContinueWith(_ =>
            {
                if (finder.Result)
                {
                    Console.WriteLine("Found TV");
                }
                else
                {
                    Console.WriteLine("No TV found");
                }
            }, tsContext);

        }
```

The issue here is TaskScheduler.FromCurrentSynchronizationContext() is having issues getting a context. I've only tested this library with WinForms so your current situation may be different as it looks like your using some libraries I've never seen before.

What I've done to fix this is tried to get the context from the app entry point instead of in OnStart() then store that in a variable and pass that into the Task.

**Comment by Hydro8** [comment]
Thank for your fast reply !

I try but i've got this error now :

`Error	1	An object reference is required for the non-static field, method, or property 'Panasonic.Program.tsContext'	C:\Users\e.laville\Documents\Visual Studio 2013\Projects\Panasonic\Panasonic\Program.cs	23	13	Panasonic
`

**Comment by logic-dev** [comment]
Sorry, I can't provide any more assistance with this. It appears you are using some custom code which I am not familiar. You need to find a way to get a task scheduler context in your current situation.
